twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        fos_csrf_provider: "@security.csrf.token_manager"
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
    - 'bootstrap_4_horizontal_layout.html.twig'
    - '@FOSCKEditor/Form/ckeditor_widget.html.twig'